name: Build Kanvas-GUI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.15.1*
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.1*
    - name: Install dependencies
      run: npm install
    #- name: Lint
    #  run: npm run lint
     
    - name: Build
      run: npm run build -- --prod
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to DockerHub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
#     - name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: ${{ secrets.DOCKERHUB_USERNAME }}/kanvas-frontend:latest
    
#     - name: Image digest
#       run: echo ${{ steps.docker_build.outputs.digest }}

# name: Build Kanvas-GUI

# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: 'Checkout'
#       uses: actions/checkout@v2

#     - name: 'Use Node'
#       uses: actions/setup-node@v1
#       with: 
#         node-version: 16.14.*

#     - name: 'Install npm'
#       run: npm i

#     - name: 'Build project'
#       run: CI=false npm run-script build
